name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    outputs:
      base_url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_MUSHROOM_0A50E5710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'dist'
  run_tests:
    if: needs.build_and_deploy.result == 'success'
    name: Run Tests - ${{ matrix.project }}
    needs: build_and_deploy
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    strategy:
      matrix:
        project: [chromium, webkit, firefox]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npx playwright test --project=${{ matrix.project }}
        env:
          CI: true
          PW_BASE_URL: ${{ needs.build_and_deploy.outputs.base_url }}
      - name: Rename blob-reports
        run: for file in blob-report/*; do [ -f "$file" ] && mv "$file" "blob-report/${{ matrix.project }}-$(basename "$file")"; done
      - name: Upload blob report
        uses: actions/upload-artifact@v4
        with:
          name: all-blob-reports-${{ matrix.project }}-${{ strategy.job-index }}
          path: blob-report
          retention-days: 1
  merge_reports:
    name: Merge Reports
    if: needs.run_tests.result == 'success'
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          pattern: all-blob-reports-*
          merge-multiple: true
          path: all-blob-reports
      - name: Rename reports
        run: count=1; for file in $(find ./all-blob-reports -maxdepth 1 -type f -name "*.zip"); do mv "$file" "all-blob-reports/report-$count.zip"; count=$((count+1)); done
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report-attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 90
